# Generated by Django 4.0.4 on 2022-07-05 17:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('address', models.CharField(max_length=255)),
                ('port', models.CharField(max_length=20)),
                ('last_check', models.DateTimeField(default=django.utils.timezone.now, verbose_name='last check')),
                ('last_status_change', models.DateTimeField(default=django.utils.timezone.now, verbose_name='last status change')),
                ('status_info', models.CharField(blank=True, default='', max_length=200)),
                ('network', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4')),
                ('circuit', models.IntegerField(blank=True, null=True)),
                ('retries', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=0)),
                ('local', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.IntegerField(choices=[(0, 'secondary'), (1, 'positive'), (2, 'primary'), (3, 'warning'), (4, 'negative')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='HostLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'secondary'), (1, 'positive'), (2, 'primary'), (3, 'warning'), (4, 'negative')], default=0)),
                ('status_change', models.DateTimeField()),
                ('status_info', models.CharField(blank=True, default='', max_length=200)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.host')),
            ],
        ),
    ]
