# Generated by Django 4.0.4 on 2022-07-13 21:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_remove_host_set_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Set time')),
            ],
        ),
    ]
