# Generated by Django 4.0.4 on 2022-07-15 16:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='set_time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Set time'),
        ),
    ]
