# Generated by Django 4.0.4 on 2022-07-18 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0007_alter_time_set_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='time',
            name='set_time',
        ),
        migrations.AddField(
            model_name='time',
            name='set_hours',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='time',
            name='set_minutes',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='time',
            name='set_seconds',
            field=models.IntegerField(default=True),
        ),
    ]
