# Generated by Django 4.0.4 on 2022-07-19 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0009_alter_time_set_hours_alter_time_set_minutes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='set_hours',
            field=models.IntegerField(max_length=2),
        ),
        migrations.AlterField(
            model_name='time',
            name='set_minutes',
            field=models.IntegerField(max_length=2),
        ),
        migrations.AlterField(
            model_name='time',
            name='set_seconds',
            field=models.IntegerField(max_length=2),
        ),
    ]
